"""phase7 refund_records

Revision ID: 8a69c5fc0d9a
Revises: 0f348e41f4de
Create Date: 2026-08-18 10:26:03.592168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a69c5fc0d9a'
down_revision: Union[str, None] = '0f348e41f4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['refund_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_refund_records_case_id'), 'refund_records', ['case_id'], unique=False)
    # 说明：checkpoint_* 表归 LangGraph PostgresSaver 管理（进程启动时 setup() 创建），
    # Alembic 不得删改这些表，否则全新库初始化会因"表不存在"失败。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_records_case_id'), table_name='refund_records')
    op.drop_table('refund_records')
    # ### end Alembic commands ###
