"""phase8 case description

Revision ID: ea542453fb26
Revises: 8a69c5fc0d9a
Create Date: 2026-08-18 10:41:44.695651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea542453fb26'
down_revision: Union[str, None] = '8a69c5fc0d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：checkpoint_* 表归 LangGraph PostgresSaver 管理，Alembic 不删改，
    # 否则全新库初始化会因"表不存在"失败。
    op.add_column('refund_cases', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_cases', 'description')
    # ### end Alembic commands ###
